# Generated by Django 3.2.4 on 2021-08-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_steamcode_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.TextField(unique=True, verbose_name='ID Аккаунта')),
                ('name', models.TextField(verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Телеграм',
                'verbose_name_plural': 'Телеграм',
            },
        ),
    ]
