# Generated by Django 3.2.4 on 2021-08-28 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamcode',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.account', verbose_name='Аккаунт'),
        ),
    ]
