# Generated by Django 3.2.4 on 2021-08-28 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_steamcode_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamcode',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.account', verbose_name='Аккаунт'),
        ),
    ]
