# Generated by Django 3.2.4 on 2021-09-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210922_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='codes',
        ),
        migrations.AddField(
            model_name='game',
            name='sub_id',
            field=models.TextField(default=0, verbose_name='SubID'),
            preserve_default=False,
        ),
    ]
