# Generated by Django 3.2.4 on 2021-09-22 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210922_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_code', models.PositiveIntegerField(verbose_name='Код продажи')),
                ('name', models.TextField(verbose_name='Название игры')),
                ('sub_id', models.PositiveIntegerField(verbose_name='SubID')),
                ('status', models.TextField(verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.account', verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
