# Generated by Django 3.2.4 on 2021-09-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='link',
            field=models.TextField(default=1, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
