# Generated by Django 3.2.4 on 2021-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_account_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.TextField(default=1, verbose_name='Баланс'),
            preserve_default=False,
        ),
    ]
