# Generated by Django 3.2.4 on 2021-09-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='account',
            new_name='bot',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub_id',
        ),
        migrations.AddField(
            model_name='order',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.game', verbose_name='Игра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_link',
            field=models.TextField(default=1, verbose_name='Аккаунт покупателя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='sell_code',
            field=models.TextField(verbose_name='Код продажи'),
        ),
    ]
