# Generated by Django 3.2.4 on 2021-09-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_order_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram',
            name='tg_id',
        ),
        migrations.AddField(
            model_name='game',
            name='priority_list',
            field=models.TextField(default=1, verbose_name='Приоритеты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegram',
            name='key',
            field=models.TextField(default=1, unique=True, verbose_name='Ключ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegram',
            name='name',
            field=models.TextField(verbose_name='Имя бота'),
        ),
        migrations.DeleteModel(
            name='Key',
        ),
    ]
