# Generated by Django 3.2.4 on 2021-10-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210929_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handmade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True, verbose_name='Код')),
                ('title', models.TextField(verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Ручная страница',
                'verbose_name_plural': 'Ручные страницы',
            },
        ),
    ]
