# Generated by Django 3.2.4 on 2021-10-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_status_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_type',
            field=models.TextField(verbose_name='Тип Статуса'),
        ),
    ]
