# Generated by Django 3.2.4 on 2021-10-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20211015_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_link',
            field=models.TextField(default=1, verbose_name='Ссылка на магазин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='skype_link',
            field=models.TextField(default=1, verbose_name='Ссылка на скайп'),
            preserve_default=False,
        ),
    ]
