# Generated by Django 3.2.4 on 2021-10-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20211015_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.PositiveIntegerField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='link',
            field=models.TextField(default=1, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
