# Generated by Django 3.2.4 on 2021-10-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20211023_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('Add to Friends', 'Add to Friends'), ('Sending Gift', 'Sending Gift'), ('Check Error', 'Check Error'), ('Send Gift Error', 'Send Gift Error'), ('Add Friend Error', 'Add Friend Error'), ('Add to Friends', 'Add to Friends'), ('Gift Rejected', 'Gift Rejected'), ('Gift Received', 'Gift Received'), ('Gift Sent', 'Gift Sent'), ('Accept Request', 'Accept Request')], verbose_name='Status'),
        ),
    ]
