# Generated by Django 3.2.4 on 2021-10-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.TextField(blank=True, verbose_name='Название игры'),
        ),
    ]
