# Generated by Django 3.2.4 on 2021-10-26 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_account_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
        migrations.AlterField(
            model_name='account',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='main/guard/', verbose_name='Файл'),
        ),
        migrations.CreateModel(
            name='GamePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
