# Generated by Django 3.2.4 on 2021-10-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20211027_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во проверок'),
            preserve_default=False,
        ),
    ]
