# Generated by Django 3.2.4 on 2021-10-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_order_check_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.FloatField(blank=True, default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GamePrice',
        ),
    ]
