# Generated by Django 3.2.4 on 2021-11-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_account_shared_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='file',
        ),
    ]
